### ISSUE TITLE
class file for bolts

### ISSUE THREAD

**Issue by cleiton-tavares** [grrrian/phonegap-parse-plugin#10]
Look at me here again :blush:, so I'm with this problem when compiling for Android "class file for bolts.Task not found", and already includes bolts in his hand however when manually include'm probably including an incorrect version because the application simply closes , what version of "bolts" correct, and would not be interesting she came up with the plugin?

thks.

**Comment by grrrian** [comment]
This was fixed on June 16 if you update the plugin.
