### ISSUE TITLE
iOS didReceiveRemoteNotification not implemented

### ISSUE THREAD

**Issue by betorobson** [grrrian/phonegap-parse-plugin#14]
Hi,

I'm testing your plugin, it looks awesome, running without any crash. However, It has not implemented yet the didReceiveRemoteNotification for iOS, which means after a push arrive when the app is on foreground nothing happens.

There is any Broadcast Message trough the NSNotificationCenter to be added? Could you tell me its name?

**Comment by grrrian** [comment]
I do swizzle didReceiveRemoteNotification in CDVParsePlugin.m line 80.
To receive notifications while running in foreground, follow the instructions from the README. And don't forget, this must be done onDeviceReady (see: http://docs.phonegap.com/en/4.0.0/cordova_events_events.md.html#deviceready):

```
parsePlugin.registerCallback('onNotification', function() {

  window.onNotification = function(pnObj) {
    alert('We received this push notification: ' + JSON.stringify(pnObj));
    if (pnObj.receivedInForeground === false) {
        // TODO: route the user to the uri in pnObj
    }
  };

}, function(error) {
  console.error(error);
});
```

Then you can use this notification object in your app (in place of the TODO). The notification does not go to the Notification Center. In fact, your app cannot send a notification to the Notification Center while running-- this is not Android ;) You can schedule it to send a notification later on using another plugin, but this is questionable design.

**Comment by betorobson** [comment]
Hi,

I really know about this limitation, my aim is not show a notification when a push arrive and the app is on foreground. Actually I have followed the steps which you have mentioned above.

For sure, I know about this limitations and workarounds. Have a look in my onNotification. It is call after app is ready exactly as you suggested.

```
    window.parsePlugin.registerCallback('onNotification', function() {

        window.onNotification = function(pnObj) {
            console.info(
                '[parsePlugin] Push notification received: ' + JSON.stringify(pnObj)
            );
            if (pnObj.receivedInForeground === false){
                console.log('[parsePlugin] todo route the user to the uri in pnObj');
                // TODO: route the user to the uri in pnObj
            }
        };

    }, function(error) {
        console.error(error);
    });
```

But I can't see nothing on log trough safari debug.

I tried the code bellow but it is not fired though. :(
alert('We received this push notification: ' + JSON.stringify(pnObj));

**Comment by grrrian** [comment]
hmmm... are you sure it's not `parsePlugin.registerCallback` instead of `window.parsePlugin.registerCallback`? Can you receive notifications in background?

**Comment by betorobson** [comment]
Ow yes, in background I'm receiving all notifications. I did a copy and paste just to be sure I'm not doing nothing wrong but still the same. Also, I implemented on AppDelegate the code bellow just for a test and it's firing on Xcode Console Log.
- (void)application:(UIApplication *)application didReceiveRemoteNotification:(NSDictionary *)userInfo {
  NSLog(@"Push notification recevied: %@", userInfo);
  }

That is why I have asked you fitst if you have did it in your Plugin.

**Comment by grrrian** [comment]
Hmmm... I'm wondering if because you modified AppDelegate, the swizzled CDVParsePlugin.didReceiveRemoteNotification is not getting called. Can you remove your modifications from the native iOS code and just put an NSLog in CDVParsePlugin.didReceiveRemoteNotification (line 183 for example)?

**Comment by betorobson** [comment]
Hummm, have a look what I found there. didReceiveRemoteNotification is not at the line. It is at lines 198 and 203.

(void)noop_application:(UIApplication *)application didReceiveRemoteNotification:(NSDictionary *)userInfo fetchCompletionHandler:(void (^)(UIBackgroundFetchResult result))handler

(void)swizzled_application:(UIApplication *)application didReceiveRemoteNotification:(NSDictionary *)userInfo fetchCompletionHandler:(void (^)(UIBackgroundFetchResult result))handler

I have screenshot of what I found and also with the NSLog.
![screen shot 2015-08-31 at 6 16 50 pm](https://cloud.githubusercontent.com/assets/13212208/9590709/c1dc956a-500c-11e5-9702-7c9018942aaa.png)

**Comment by betorobson** [comment]
I didn't tell you that both NSLog were not fired when app is in foreground. :(

**Comment by betorobson** [comment]
For now, I'm thinking about fire it manually. That means implement on AppDelegate the didReceiveRemoteNotification. I know it is not a good practice but it will work anyway.

Let me know if you have any idea about this issue. Thank you :)

(void)application:(UIApplication *)application didReceiveRemoteNotification:(NSDictionary *)userInfo {
        [self.viewController javascriptAlert:@"Push notification received"];
        NSLog(@"Push notification received: %@", userInfo);
}

**Comment by grrrian** [comment]
Weird. I wonder if you have another plugin overriding didReceiveRemoteNotification. Search for didReceiveRemoteNotification to verify.

**Comment by betorobson** [comment]
I searched inside the whole project and It found just inside the CDVParsePlugin. I have installed just a few plugins, I will list them for you here:

com.parse.cordova.core.pushplugin 0.1.0 "phonegap-parse-plugin"
cordova-plugin-dialogs 1.1.1 "Notification"
cordova-plugin-file 2.1.0 "File"
cordova-plugin-file-transfer 1.2.0 "File Transfer"
cordova-plugin-network-information 1.0.1 "Network Information"
cordova-plugin-splashscreen 2.1.0 "Splashscreen"
cordova-plugin-statusbar 1.0.1 "StatusBar"
cordova-plugin-whitelist 1.0.0 "Whitelist"
hu.dpal.phonegap.plugins.SpinnerDialog 1.3.1 "SpinnerDialog"
org.apache.cordova.device 0.3.0 "Device"

There is something that I have been asking myself. If the app must call the didReceiveRemoteNotification when a push arrives, why it has been calling it on the default AppDelegate instead of from CDVParsePlugin? Do you have any idea?

I can share my project with you if this can help us to find this weir behaviour.

**Comment by grrrian** [comment]
All plugins use swizzling to override classes (this NSHipster article is the best explanation I found on swizzling: http://nshipster.com/method-swizzling/). They do this because imagine if all plugins tried modifying AppDelegate: it would be a mess in there and you would get merge conflicts.

In CDVParsePlugin.h we swizzle AppDelegate on line 15, and in CDVParsePlugin.m on line 123: 

```
@implementation AppDelegate (CDVParsePlugin)

void MethodSwizzle(Class c, SEL originalSelector) {
    NSString *selectorString = NSStringFromSelector(originalSelector);
    SEL newSelector = NSSelectorFromString([@"swizzled_" stringByAppendingString:selectorString]);
    SEL noopSelector = NSSelectorFromString([@"noop_" stringByAppendingString:selectorString]);
    Method originalMethod, newMethod, noop;
    originalMethod = class_getInstanceMethod(c, originalSelector);
    newMethod = class_getInstanceMethod(c, newSelector);
    noop = class_getInstanceMethod(c, noopSelector);
    if (class_addMethod(c, originalSelector, method_getImplementation(newMethod), method_getTypeEncoding(newMethod))) {
        class_replaceMethod(c, newSelector, method_getImplementation(originalMethod) ?: method_getImplementation(noop), method_getTypeEncoding(originalMethod));
    } else {
        method_exchangeImplementations(originalMethod, newMethod);
    }
}

+ (void)load
{
    MethodSwizzle([self class], @selector(application:didRegisterForRemoteNotificationsWithDeviceToken:));
    MethodSwizzle([self class], @selector(application:didReceiveRemoteNotification:fetchCompletionHandler:));
    MethodSwizzle([self class], @selector(application:didFinishLaunchingWithOptions:));
    MethodSwizzle([self class], @selector(applicationDidBecomeActive:));
}
```

I have no idea why this is not working for you, especially since the background notification swizzle in the same way. Sorry :(

**Comment by betorobson** [comment]
Ahhhhhhh you can't believe what I did. The method "MethodSwizzle([self class], @selector(application:didReceiveRemoteNotification:fetchCompletionHandler:));" only works on iOS 7 or later. My ipod touch is iOS 6. OMG!!!! I already tried it in a friend iOS 7 device and it works perfect!!!!!!

I'm sorry for that, that was really stupid from my part. Your plugin is awesome!!!!!

Thank you!!!!

**Comment by grrrian** [comment]
Lol, glad you figured it out. I wasn't aware iOS6 didn't have that feature. I'll add it to the README. Thanks!
