### ISSUE TITLE
Parse tells me no registered devices but I can see Installations

### ISSUE THREAD

**Issue by urbanmania** [grrrian/phonegap-parse-plugin#16]
Not sure what's going on with my app so I thought I'd post here to see if anyone else had experienced it.  I did not run into this problem with a previous app and think I've done everything the same, but I might be wrong.

So, I've set up the app and I can see Installations, with device tokens in the Parse Data view and they are subscribed to the channels I set up in the code.  However, when I go to send a sample push I'm told that there are no registered devices and even when I go into the quick intro and click the "Test" button, I get an error.

Any ideas?

**Comment by grrrian** [comment]
Did you add your push certificate p12 file in the parse settings?

ian

**Comment by urbanmania** [comment]
DOH!!!!

How can one be so stupid!!  That was it. Did forget that important step.  Now at least one of my devices gets the push.  Thanks so much!!!

**Comment by grrrian** [comment]
Welcome

ian

**Comment by urbanmania** [comment]
Hum, it only sends to one of my devices. I haven't dared to build on that device again as I'm afraid that will break it.  If I push to a channel that does not include that device no push gets sent.  The Installations data looks OK though, any idea? (sorry for being a pain)

**Comment by urbanmania** [comment]
Figured it out :)
