### ISSUE TITLE
Anyway to customise the icon on Android

### ISSUE THREAD

**Issue by niraj-shah** [grrrian/phonegap-parse-plugin#18]
Sending a push to Android shows a default white icon. Is there anyway to customise the icon so I can specify a custom image?

**Comment by grrrian** [comment]
You would have to customize the plugin for that. By default, Android should use your app icon if no image is specified. 

ian

**Comment by niraj-shah** [comment]
I found a easier way. Adding the following line to `platforms/android/AndroidManifest.xml` file (between the `<application ...></application>` tags) lets you specify a custom icon:

```
<meta-data android:name="com.parse.push.notification_icon" android:resource="@drawable/push_icon" />
```

You can then drop in icons into the `platforms/android/res/drawable-.../` folders (I named them push_icon.png). The following icon sizes are needed:
- `platforms/android/res/drawable-mdpi/`: 24px × 24px
- `platforms/android/res/drawable-hdpi/`: 36px × 36px
- `platforms/android/res/drawable-xhdpi/`: 48px × 48px
- `platforms/android/res/drawable-xxhdpi/`: 72px × 72px
- `platforms/android/res/drawable-xxxhdpi/`: 96px × 96px
