### ISSUE TITLE
Integration with sqlite

### ISSUE THREAD

**Issue by jlno** [grrrian/phonegap-parse-plugin#19]
Save push message with sqlite on "onPushReceive" method.
https://github.com/litehelpers/Cordova-sqlite-storage

**Comment by grrrian** [comment]
Not a bad idea but I will not implement this in the near future. All my notifications are already stored on my backend server. Why don't you use that approach?

ian

**Comment by jlno** [comment]
I do not know much about java.
I instantiate the class of sqlite, but not call any method @Override.

**Comment by grrrian** [comment]
Why don't you just do it in JavaScript in your app?

ian

**Comment by jlno** [comment]
Because the function onNotification (registerCallback) is called only when I click on the push message, or when the app is opened.

**Comment by jlno** [comment]
When I click to see the push message, the onNotification function returns only the data of the selected push message. Should return all push messages.

**Comment by jlno** [comment]
I am implementing, is almost ready.

**Comment by jlno** [comment]
It worked what I wanted to do.
