### ISSUE TITLE
Android Issue

### ISSUE THREAD

**Issue by Gauloix** [grrrian/phonegap-parse-plugin#2]
When building Android project, got this error :

```
cannot access bolts.Task
    [javac] class file for bolts.Task not found
    [javac]                     ParseInstallation.getCurrentInstallation().saveInBackground();
```

There is no bolts-android-1.1.4.jar in platforms/android/libs.

thank you @grrrian !

**Comment by Gauloix** [comment]
I manually copied bolts-android-1.1.4.jar in platforms/android/libs.

Now, I can build and run the app.
parsePlugin.initialize is working.

parsePlugin.subscribe fail and crash the app.

In adb logcat, I have found this :

```
E/AndroidRuntime(19435): FATAL EXCEPTION: pool-2-thread-2
E/AndroidRuntime(19435): Process: com.project.app, PID: 19435
E/AndroidRuntime(19435): java.lang.IllegalStateException: PushService.subscribe, PushService.unsubscribe, and PushService.setDefaultPushCallback methods cannot be used in conjunction with ParsePushBroadcastReceiver. See ParsePush.subscribe and ParsePush.unsubscribe.
E/AndroidRuntime(19435):    at com.parse.PushService.checkManifestAndThrowExceptionIfNeeded(PushService.java:417)
E/AndroidRuntime(19435):    at com.parse.PushService.subscribe(PushService.java:297)
E/AndroidRuntime(19435):    at com.parse.PushService.subscribe(PushService.java:262)
E/AndroidRuntime(19435):    at org.apache.cordova.core.ParsePlugin$6.run(ParsePlugin.java:147)
E/AndroidRuntime(19435):    at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1112)
E/AndroidRuntime(19435):    at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:587)
E/AndroidRuntime(19435):    at java.lang.Thread.run(Thread.java:818)
W/ActivityManager(  778):   Force finishing activity com.project.app/.MainActivity
```

Any idea ?

**Comment by grrrian** [comment]
Ok, it seems like you have installed plugins on top of one another and they are conflicting. My plugin does not use setDefaultPushCallback.

You probably installed avivais' branch before installing mine. You should of uninstalled his plugin first.

I would make a backup of what you have (or use some sort of source control system like Git), then using the command line: 
1. uninstall the plugin: `$ cordova platform rm com.parse.cordova.core.pushplugin`
2. re-install from my repo: `$ cordova plugin add https://github.com/grrrian/phonegap-parse-plugin --variable APP_ID=PARSE_APP_ID --variable CLIENT_KEY=PARSE_CLIENT_KEY`

If this was not enough, try removing platforms/android: `$ cordova platform rm android` and repeat steps 1 and 2.

**Comment by grrrian** [comment]
Never mind, there was actually a bug in the code. I fixed it but I didn't have the time to test it-- I don't use subscriptions in my app. Can you pull my latest branch and try it out? Good luck!
