### ISSUE TITLE
Not receiving notifications when app is closed

### ISSUE THREAD

**Issue by cktg** [grrrian/phonegap-parse-plugin#4]
May I know what to look out for in plugin.xml to get the app to receive notification when it is closed?

"To receive notifications on Android when the app is closed (not running in foreground nor background), follow the instructions in plugin.xml."

Thank you

**Comment by iblazevic** [comment]
I don't think you need to look for anything specific there, not sure why is that sentence there, it should work with instructions from README, make sure to go through android quirks

**Comment by grrrian** [comment]
Indeed. I removed it from the README. The setup is now down at the command line as explained in the README.

**Comment by aaronksaunders** [comment]
this works fine for me, just pulled the plugin over the weekend

**Comment by grrrian** [comment]
Thanks Aaron

ian
