### ISSUE TITLE
READ.ME confusion

### ISSUE THREAD

**Issue by aaronksaunders** [grrrian/phonegap-parse-plugin#5]
Just a quick note, not sure how to resolved... since your fork is not the same as the original, copying the installation command line code cause some problems for me initially as I installed the incorrect plugin.

The readme instructions install `avivais/phonegap-parse-plugin` not your plugin

**Comment by grrrian** [comment]
Yea... All you need to do is remove the plugin ($cordova rm com.blabla) then reinstall mine (grrrian). I did not change the installation instructions because this branch was meant to be merge back into avivais. 

ian
