### ISSUE TITLE
Not working iOS 8.4 xCode 6.4

### ISSUE THREAD

**Issue by matmac** [grrrian/phonegap-parse-plugin#6]
I've installed the plugin from your repo and suddenly i can't build.

Using iOS 8.4 and xCode 6.4, seems the architectures are the problem here since it throws errors on both i386 and armv7 but im not sure.

**Comment by grrrian** [comment]
Thanks for the heads up. I'll take a look

ian

**Comment by grrrian** [comment]
Can you give more info on the issue? I cannot reproduce this. Was this fork working with 8.3? Is avivais branch working on 8.4?

**Comment by urbanmania** [comment]
Just my 2 cents - I have been able to build no problems using iOS 8.4 and XCode 6.4, both while they were in Beta and now after those two have been released.

**Comment by grrrian** [comment]
Thanks @urbanmania

**Comment by dotfrank** [comment]
Same behavior - building no problem with 8.4.
